import pathlib

NUM_MODELS = 30
NUM_FOLDS = 5
# MODEL NAME
INPUT_SIZE, FILTERS = 500, 64
RDIR = pathlib.Path(f"Results/RES_{INPUT_SIZE}_{FILTERS}_09")
##
MDIR = RDIR / f"RES_{INPUT_SIZE}_{FILTERS}"
CDIR = RDIR / f"Checkpoints/RES_{INPUT_SIZE}_{FILTERS}_CHECKPOINT"
CVDIR = RDIR / f"RES_{INPUT_SIZE}_CROSS_VAL"
